name: My first workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List and read files
      run: | 
        echo "Welcome to GitHub Actions"
        ls -ltrh
        cat README.md

    - name: Generate ASCII art
      run: cowsay -f dragon "Run for cover, I am DRAGON.....RAWR" >> dragon.txt
       