name: Generate ASCII art
on: [push]
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Cowsay
      run: sudo apt-get install cowsay

    - name: Generate ASCII art
      run: cowsay -f dragon "Run for cover, I am DRAGON.....RAWR" >> dragon.txt

    - name: Upload dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-txt-file
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-txt-file

    - name: Test file existence
      run: grep -i "DRAGON" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-txt-file

    - name: Read ASCII art
      run: cat dragon.txt
    
    