name: Generate ASCII art
on: [push]
jobs:
  ascii-art:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List Repo files
      run: ls -ltrh
    
    - name: Verify ascii-script.sh exists
      run: test -f ascii-script.sh && echo "File exists" || echo "File does not exist"
      
    - name: Executing Shell script
      run: |
        chmod +x ascii-script.sh 
        ./ascii-script.sh