name: Generate ASCII art
on: [push]
jobs:
  ascii-art:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List Repo files
      run: ls -ltrh
    
    - name: Executing Shell script
      run: ./ascii-script.sh